networks:
  lab-net:
    driver: bridge

services:

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      - lab-net

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    networks:
      - lab-net

  webgoat:
    image: webgoat/webgoat
    container_name: webgoat
    ports:
      - "8080:8080"
    networks:
      - lab-net

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    ports:
      - "8090:8090"
    networks:
      - lab-net
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8090
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    depends_on:
      - juice-shop
      - dvwa
      - webgoat